server:
  port: 888

spring:
  application:
    name: usercenter-logging
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/usercenter_logging?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true

# RocketMQ配置
rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    pull-batch-size: 10

# 日志配置
logging:
  level:
    com.xzc.user: debug
    root: info

